package_assets: on
embed_assets: on
gzip_assets: on

javascripts:
  production:
    - public/javascripts/jquery.min.js
    - public/javascripts/jquery.timers.1.2.js
    - public/javascripts/application.js
    - public/javascripts/rails.js
    - public/javascripts/jquery.jplayer.min.js
    - public/javascripts/chosen.jquery.js
    - public/javascripts/bootstrap-dropdown.js
    - public/javascripts/jquery.jeditable.mini.js
    - public/javascripts/jquery.jeditable.checkbox.js
    - public/javascripts/on_the_spot.js
  analytics:
    - public/javascripts/google.js

stylesheets:
  common:
    - public/stylesheets/reset.css
    - public/stylesheets/chosen.css
    - public/stylesheets/bootstrap-1.2.0.min.css
    - public/stylesheets/override.css